### ISSUE TITLE
Add CI Workflow to Run Tests Automatically

### ISSUE THREAD

**Issue by scansio** [scyberLink/ruig#30]
We need a **GitHub Actions workflow** to automatically run tests on pull requests.  

#### **Steps to Complete:**  
1. Create `.github/workflows/test.yml`:  
   ```yaml
   name: Run Tests
   on: [push, pull_request]
   jobs:
     test:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
             node-version: 18
         - run: npm install
         - run: npm test
   ```  
2. Push and ensure tests run on GitHub.  

---
