### ISSUE TITLE
Automate NPM Package Deployment with GitHub Actions

### ISSUE THREAD

**Issue by scansio** [scyberLink/ruig#36]
Our repository currently lacks an automated deployment process for publishing the RUIG npm package. To streamline our release process and reduce manual errors, we should set up a GitHub Actions workflow that automatically deploys the npm package when a new release is created or when changes are pushed to the main branch (as appropriate).  

#### **Proposed Solution:**  
- **Create a GitHub Actions Workflow:**  
  Develop a workflow file (e.g., `.github/workflows/npm-publish.yml`) that handles the following:  
  - **Node Setup:** Use `actions/setup-node` to configure the required Node.js version and cache dependencies.  
  - **Authentication:** Utilize an npm authentication token (stored securely in GitHub Secrets as `NPM_TOKEN`) to allow publishing.  
  - **Build and Test:** Run build scripts and tests to ensure the package is production-ready before publishing.  
  - **Conditional Publishing:** Trigger the deployment on a new release (or push to main), ensuring version consistency and changelog updates.  

- **Workflow Triggers:**  
  Configure the workflow to trigger on specific events such as:  
  - Creation of a new GitHub release (preferred for controlled deployments).  
  - Alternatively, on push events to the main branch (if that suits our release strategy).

#### **Steps to Complete:**  
1. **Create Workflow File:**  
   - Add a new file at `.github/workflows/npm-publish.yml`.  
   - Define triggers (e.g., on release creation) and steps to set up Node.js, install dependencies, run tests, build the package, and finally publish using `npm publish`.

2. **Configure Secrets:**  
   - Ensure that an `NPM_TOKEN` is set up in the repository’s GitHub Secrets for secure authentication.

3. **Test the Workflow:**  
   - Test the workflow in a fork or a separate branch to confirm that the npm package is built and published correctly without manual intervention.
  
4. **Documentation:**  
   - Update the repository’s README or CONTRIBUTING documentation to explain the automated deployment process and any necessary prerequisites for release maintainers.

#### **Example Workflow Snippet:**
```yaml
name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Package
        run: npm run build

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
```

#### **Benefits:**  
- **Streamlined Releases:** Automation reduces manual steps and minimizes human error during deployment.  
- **Consistent Quality:** Ensures that only tested and verified code is published.  
- **Enhanced Productivity:** Saves time for maintainers, allowing them to focus on development rather than manual deployments.

Let's get this in place and make our release process as smooth as our drag-and-drop UI builder! 🚀
